---
all:
  vars:
    cluster_name: "demoinfra"
    cluster_env_domain: "mosip.local"
    k8s_infra_repo_url: "https://github.com/mosip-asia/k8s-infra.git"
    k8s_infra_branch: "demo"
    install_rke2_version: "v1.28.9+rke2r1"
    enable_rancher_import: true
    rancher_import_url: "kubectl apply -f https://rancher.demo.mosip.sandbox.cs.ait.ac.th/v3/import/9nxmh42wgpffmq4lrrmtfxt2gh5776lnj7sk92k47rf5wtlv5llmlp_c-m-llnrfr5j.yaml"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ./ssh_key
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  children:
    control_plane:
      hosts:
        demoinfra-CONTROL-PLANE-NODE-1:
          ansible_host: 10.0.4.123
          node_role: control_plane
          is_primary: true
          node_index: 0
        demoinfra-CONTROL-PLANE-NODE-2:
          ansible_host: 10.0.4.94
          node_role: control_plane
          is_primary: false
          node_index: 1
        demoinfra-CONTROL-PLANE-NODE-3:
          ansible_host: 10.0.4.75
          node_role: control_plane
          is_primary: false
          node_index: 2
    
    etcd:
      hosts:
        demoinfra-ETCD-NODE-1:
          ansible_host: 10.0.4.145
          node_role: etcd
        demoinfra-ETCD-NODE-2:
          ansible_host: 10.0.4.246
          node_role: etcd
        demoinfra-ETCD-NODE-3:
          ansible_host: 10.0.4.205
          node_role: etcd
    
    workers:
      hosts:
        demoinfra-WORKER-NODE-1:
          ansible_host: 10.0.4.131
          node_role: worker
        demoinfra-WORKER-NODE-2:
          ansible_host: 10.0.4.217
          node_role: worker

    rke2_cluster:
      children:
        control_plane:
        etcd:
        workers:
